# azure-pipelines.yml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: configuration
  displayName: Configuration
  type: string
  default: 'no'
  values:
  - 'yes'
  - 'no'

steps:
- task: Checkout@1
  inputs:
    repository: 'https://github.com/vipul71098/pod_deploy'

- script: |
    echo "Building Docker image..."
    docker build -t my-docker-image:latest .
  displayName: 'Build Docker Image'


- script: |
    if [ '${{ parameters.configuration }}' == 'yes' ]; then
      echo "Deleting Docker image..."
      docker rmi my-docker-image:latest || true
    else
      echo "Skipping Docker image deletion."
    fi
  displayName: 'Delete Docker Image'
  condition: always()  # Ensure this step runs regardless of previous steps' success
