trigger:
- main

pool:
  name: 'vips-agent'  # Specify your custom agent pool here

parameters:
- name: delete_docker_image
  displayName: Delete Docker Image
  type: string
  default: 'no'
  values:
  - 'yes'
  - 'no'

steps:
- checkout: self  # Use 'self' to check out the repository where the YAML is located

- script: |
    echo "Building Docker image..."
    docker build -t test.azurecr.io/qa:$(Build.BuildId) .
    docker build -t test.azurecr.io/qa-azurequeueimport:$(Build.BuildId) .
    docker build -t test.azurecr.io/qa-azurequeuepayroll:$(Build.BuildId) .
  displayName: 'Build Docker Image'

- powershell: |
    $config = '${{ parameters.delete_docker_image }}'
    if ($config -eq 'yes') {
      Write-Output "Deleting Docker image..."
      docker rmi my-docker-image:latest -f
    } else {
      Write-Output "Retagging Docker images to dev..."
      docker tag test.azurecr.io/qa:$(Build.BuildId) test.azurecr.io/dev:$(Build.BuildId)
      docker tag test.azurecr.io/qa-azurequeueimport:$(Build.BuildId) test.azurecr.io/dev-azurequeueimport:$(Build.BuildId) 
      docker tag test.azurecr.io/qa-azurequeuepayroll:$(Build.BuildId) test.azurecr.io/dev-azurequeuepayroll:$(Build.BuildId)
    }
  displayName: 'Delete or Retag Docker Images'
  condition: always()  # Ensure this step runs regardless of the success of previous steps
