trigger:
- main

pool:
  name: 'vips-agent'  # Specify your custom agent pool here

parameters:
- name: delete_docker_image
  displayName: Delete Docker Image
  type: string
  default: 'no'
  values:
  - 'yes'
  - 'no'

# steps:
# - checkout: self  # Use 'self' to check out the repository where the YAML is located

steps:
- powershell: Get-ChildItem Env:
  displayName: 'Print All Environment Variables'


- script: |
    printenv
    echo "Building Docker images..."
    docker build -t vipstest.azurecr.io/qa:$(Build.BuildNumber) .
    echo "Built Docker image: vipstest.azurecr.io/qa:$(Build.BuildNumber)"
    
    docker build -t vipstest.azurecr.io/qa-azurequeueimport:$(Build.BuildNumber) .
    echo "Built Docker image: vipstest.azurecr.io/qa-azurequeueimport:$(Build.BuildNumber)"
    
    docker build -t vipstest.azurecr.io/qa-azurequeuepayroll:$(Build.BuildNumber) .
    echo "Built Docker image: vipstest.azurecr.io/qa-azurequeuepayroll:$(Build.BuildNumber)"
    
    docker push vipstest.azurecr.io/qa:$(Build.BuildNumber)
    echo "Pushed Docker image: vipstest.azurecr.io/qa:$(Build.BuildNumber)"
    
    docker push vipstest.azurecr.io/qa-azurequeueimport:$(Build.BuildNumber)
    echo "Pushed Docker image: vipstest.azurecr.io/qa-azurequeueimport:$(Build.BuildNumber)"
    
    docker push vipstest.azurecr.io/qa-azurequeuepayroll:$(Build.BuildNumber)
    echo "Pushed Docker image: vipstest.azurecr.io/qa-azurequeuepayroll:$(Build.BuildNumber)"
  displayName: 'Build and Push Docker Images'

- powershell: |
    $config = '${{ parameters.delete_docker_image }}'
    if ($config -eq 'yes') {
      Write-Host "Deleting Docker images with build number $(Build.BuildNumber)"
      
      docker rmi vipstest.azurecr.io/qa:$(Build.BuildNumber)
      Write-Host "Deleted Docker image: vipstest.azurecr.io/qa:$(Build.BuildNumber)"
      
      docker rmi vipstest.azurecr.io/qa-azurequeueimport:$(Build.BuildNumber)
      Write-Host "Deleted Docker image: vipstest.azurecr.io/qa-azurequeueimport:$(Build.BuildNumber)"
      
      docker rmi vipstest.azurecr.io/qa-azurequeuepayroll:$(Build.BuildNumber)
      Write-Host "Deleted Docker image: vipstest.azurecr.io/qa-azurequeuepayroll:$(Build.BuildNumber)"
    } else {
      Write-Host "Retagging Docker images to dev with build number $(Build.BuildNumber)"
      
      docker tag vipstest.azurecr.io/qa:$(Build.BuildNumber) vipstest.azurecr.io/dev:$(Build.BuildNumber)
      Write-Host "Tagged Docker image as: vipstest.azurecr.io/dev:$(Build.BuildNumber)"
      
      docker tag vipstest.azurecr.io/qa-azurequeueimport:$(Build.BuildNumber) vipstest.azurecr.io/dev-azurequeueimport:$(Build.BuildNumber)
      Write-Host "Tagged Docker image as: vipstest.azurecr.io/dev-azurequeueimport:$(Build.BuildNumber)"
      
      docker tag vipstest.azurecr.io/qa-azurequeuepayroll:$(Build.BuildNumber) vipstest.azurecr.io/dev-azurequeuepayroll:$(Build.BuildNumber)
      Write-Host "Tagged Docker image as: vipstest.azurecr.io/dev-azurequeuepayroll:$(Build.BuildNumber)"
      
      docker push vipstest.azurecr.io/dev:$(Build.BuildNumber)
      Write-Host "Pushed Docker image: vipstest.azurecr.io/dev:$(Build.BuildNumber)"
      
      docker push vipstest.azurecr.io/dev-azurequeueimport:$(Build.BuildNumber)
      Write-Host "Pushed Docker image: vipstest.azurecr.io/dev-azurequeueimport:$(Build.BuildNumber)"
      
      docker push vipstest.azurecr.io/dev-azurequeuepayroll:$(Build.BuildNumber)
      Write-Host "Pushed Docker image: vipstest.azurecr.io/dev-azurequeuepayroll:$(Build.BuildNumber)"
    }
  displayName: 'Delete or Retag Docker Images'
