trigger:
- main

pool:
  name: 'vips-agent'  # Specify your custom agent pool here

parameters:
- name: configuration
  displayName: Configuration
  type: string
  default: 'no'
  values:
  - 'yes'
  - 'no'

steps:
- checkout: self  # Use 'self' to check out the repository where the YAML is located

- script: |
    echo "Building Docker image..."
    docker build -t my-docker-image:latest .
  displayName: 'Build Docker Image'

- script: |
    if [ '${{ parameters.configuration }}' == 'yes' ]; then
      echo "Deleting Docker image..."
      docker rmi my-docker-image:latest || true
    else
      echo "Skipping Docker image deletion."
    fi
  displayName: 'Delete Docker Image'
