trigger:
- main

pool:
  name: 'vips-agent'  # Specify your custom agent pool here

parameters:
- name: delete_docker_image
  displayName: Delete Docker Image
  type: string
  default: 'no'
  values:
  - 'yes'
  - 'no'

steps:
- checkout: self  # Use 'self' to check out the repository where the YAML is located

- script: |
    echo "Building Docker image..."
    docker build -t my-docker-image:latest .
    docker build -t test.azurecr.io/qa:12345 .
    docker build -t test.azurecr.io/qa-azurequeueimport:20240904.5 .
    docker build -t test.azurecr.io/qa-azurequeuepayroll:20240904.5 .
  displayName: 'Build Docker Image'

- powershell: |
    $config = '${{ parameters.delete_docker_image }}'
    if ($config -eq 'yes') {
      Write-Output "Deleting Docker image..."
      docker rmi my-docker-image:latest -f
    } else {
      Write-Output "Retagging Docker images to dev..."
      docker tag test.azurecr.io/qa:12345 test.azurecr.io/dev:12345
      docker tag test.azurecr.io/qa-azurequeueimport:20240904.5 test.azurecr.io/dev-azurequeueimport:20240904.5 
      docker tag test.azurecr.io/qa-azurequeuepayroll:20240904.5 test.azurecr.io/dev-azurequeuepayroll:20240904.5
    }
  displayName: 'Delete or Retag Docker Images'
  condition: always()  # Ensure this step runs regardless of the success of previous steps
